export const rangeUpdateRangeQueryQuiz = [
  { question: 'What is the purpose of the lazy array in a Segment Tree with Lazy Propagation?', options: ['To store the minimum of each segment', 'To defer pending updates that have not yet been pushed to children', 'To store the index of each element', 'To track visited nodes during queries'], correctAnswer: 'To defer pending updates that have not yet been pushed to children', explanation: 'The lazy array stores pending updates at each node so that range updates can be applied in O(log n) without updating every element immediately.' },
  { question: 'What is the time complexity of a range update using Lazy Propagation?', options: ['O(n)', 'O(n log n)', 'O(log n)', 'O(1)'], correctAnswer: 'O(log n)', explanation: 'Lazy Propagation defers updates to covered segments, so a range update only visits O(log n) nodes.' },
  { question: 'When must a lazy tag be pushed down to children?', options: ['Only during build', 'Before recursing into children during a query or update', 'After every update regardless', 'Only when the lazy value is negative'], correctAnswer: 'Before recursing into children during a query or update', explanation: 'Push down must happen before going deeper into the tree to ensure children have up-to-date values before being queried or updated.' },
  { question: 'What is the correct formula to update a child node sum when pushing down a lazy value of val from a parent?', options: ['child_sum += val', 'child_sum += val * child_segment_length', 'child_sum = val', 'child_sum *= val'], correctAnswer: 'child_sum += val * child_segment_length', explanation: 'The lazy value applies to every element in the child segment, so the sum increases by val multiplied by the number of elements in that segment.' },
  { question: 'After pushing down a lazy tag from a parent to its children, what should happen to the parent lazy tag?', options: ['It should be doubled', 'It should be set to -1', 'It should be reset to 0', 'It should be copied to the grandparent'], correctAnswer: 'It should be reset to 0', explanation: 'Once the lazy tag is pushed to children, the parent no longer has a pending update, so its lazy tag is reset to 0.' },
  { question: 'What does lazy[node] = 5 mean in a Segment Tree with Lazy Propagation?', options: ['The node sum is 5', 'Every element in this node segment needs 5 added, but it has not been pushed to children yet', 'The node has 5 children', 'The segment starts at index 5'], correctAnswer: 'Every element in this node segment needs 5 added, but it has not been pushed to children yet', explanation: 'A lazy tag of 5 means a pending addition of 5 to every element in the segment, deferred until a push down is triggered.' },
  { question: 'Which of the following operations requires Lazy Propagation to achieve O(log n)?', options: ['Point update', 'Point query', 'Range update followed by range query', 'Building the segment tree'], correctAnswer: 'Range update followed by range query', explanation: 'Without lazy propagation, a range update would take O(n) to update every element. Lazy propagation defers this work to achieve O(log n).' },
  { question: 'What is the space complexity of a Segment Tree with Lazy Propagation for an array of size n?', options: ['O(log n)', 'O(n)', 'O(n log n)', 'O(4n)'], correctAnswer: 'O(4n)', explanation: 'Both the tree array and the lazy array require 4*n space each, giving O(n) overall space (with constant factor 4).' },
  { question: 'In a range query [l, r], what is returned when the current segment is completely outside [l, r]?', options: ['0', '-1', 'The node sum', 'Infinity'], correctAnswer: '0', explanation: 'For a sum query, returning 0 for out-of-range segments ensures it does not affect the accumulated sum.' },
  { question: 'Which of the following is NOT a valid extension of Lazy Propagation?', options: ['Range assignment (set all elements in range to a value)', 'Range multiply', 'Range addition', 'Range binary search'], correctAnswer: 'Range binary search', explanation: 'Lazy Propagation supports range assignment, multiply, and addition by adjusting the lazy tag and push down logic. Range binary search is a different technique unrelated to lazy propagation.' },
];
