export const redundantConnectionQuiz = [
  { question: 'What is the goal of the Redundant Connection problem?', options: ['Find the shortest path between two nodes', 'Find the edge that creates a cycle in an undirected graph', 'Count the number of connected components', 'Find the minimum spanning tree'], correctAnswer: 'Find the edge that creates a cycle in an undirected graph', explanation: 'The problem asks us to return the last edge added that forms a cycle, making it redundant in a tree structure.' },
  { question: 'Which data structure is most commonly used to solve Redundant Connection efficiently?', options: ['Stack', 'Queue', 'Union-Find (Disjoint Set Union)', 'Binary Search Tree'], correctAnswer: 'Union-Find (Disjoint Set Union)', explanation: 'Union-Find allows us to efficiently check if two nodes are already connected and union them if not, detecting the cycle-forming edge.' },
  { question: 'What does the find() operation do in Union-Find?', options: ['Merges two components', 'Returns the root/representative of a node\'s component', 'Counts the number of components', 'Deletes a node from the graph'], correctAnswer: 'Returns the root/representative of a node\'s component', explanation: 'find() traverses the parent pointers to return the root of the component that a node belongs to.' },
  { question: 'When is an edge considered redundant in this problem?', options: ['When it connects two nodes with the same label', 'When both its endpoints already belong to the same connected component', 'When it is the longest edge in the graph', 'When it connects a node to itself'], correctAnswer: 'When both its endpoints already belong to the same connected component', explanation: 'If find(u) == find(v) before processing edge (u, v), then u and v are already connected, so adding this edge creates a cycle.' },
  { question: 'What is the time complexity of Union-Find with path compression and union by rank?', options: ['O(n^2)', 'O(n log n)', 'O(n * alpha(n))', 'O(1)'], correctAnswer: 'O(n * alpha(n))', explanation: 'With path compression and union by rank, each operation runs in O(alpha(n)) — the inverse Ackermann function — which is practically constant.' },
  { question: 'What is the space complexity of the Union-Find approach for Redundant Connection?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n^2)'], correctAnswer: 'O(n)', explanation: 'We store a parent array and a rank array, each of size n+1, giving O(n) space.' },
  { question: 'In the Redundant Connection problem, how many edges does the input graph have?', options: ['n-1', 'n', 'n+1', '2n'], correctAnswer: 'n', explanation: 'The graph has n nodes and n edges. A tree with n nodes has n-1 edges, so exactly one extra edge is added creating a cycle.' },
  { question: 'What does path compression do in Union-Find?', options: ['Removes edges from the graph', 'Makes every node point directly to the root during find()', 'Sorts the nodes by rank', 'Splits a component into two'], correctAnswer: 'Makes every node point directly to the root during find()', explanation: 'Path compression flattens the tree structure so future find() calls are faster by making nodes point directly to the root.' },
  { question: 'What does union by rank do in Union-Find?', options: ['Always attaches the first tree under the second', 'Attaches the shorter tree under the root of the taller tree', 'Removes the smaller component', 'Sorts nodes alphabetically'], correctAnswer: 'Attaches the shorter tree under the root of the taller tree', explanation: 'Union by rank keeps the tree shallow by always attaching the tree with lower rank under the tree with higher rank, improving efficiency.' },
  { question: 'If edges = [[1,2],[1,3],[2,3]], which edge is the redundant connection?', options: ['[1,2]', '[1,3]', '[2,3]', 'None'], correctAnswer: '[2,3]', explanation: 'After processing [1,2] and [1,3], nodes 1, 2, and 3 are all connected. Adding [2,3] creates a cycle, so it is the redundant edge.' },
];
