export const numberOfIslandsIIQuiz = [
  { question: 'What makes Number of Islands II different from the classic Number of Islands problem?', options: ['It uses BFS instead of DFS', 'Land cells are added dynamically one at a time and the count is needed after each addition', 'The grid is always square', 'It only counts islands of size greater than 1'], correctAnswer: 'Land cells are added dynamically one at a time and the count is needed after each addition', explanation: 'In Number of Islands II, land is added online (one operation at a time) and we must report the island count after each operation, making it a dynamic connectivity problem.' },
  { question: 'Which data structure is best suited for Number of Islands II?', options: ['DFS with a visited array', 'BFS with a queue', 'Union-Find (Disjoint Set Union)', 'Segment Tree'], correctAnswer: 'Union-Find (Disjoint Set Union)', explanation: 'Union-Find efficiently handles dynamic merging of components, making it ideal for tracking island counts as land cells are added.' },
  { question: 'How is a 2D grid cell (row, col) mapped to a 1D Union-Find index?', options: ['row + col', 'row * col', 'row * n + col', 'col * m + row'], correctAnswer: 'row * n + col', explanation: 'The standard mapping for a 2D grid of width n is index = row * n + col, giving each cell a unique 1D index.' },
  { question: 'When a new land cell is added, what is the initial change to the island count?', options: ['Decrease by 1', 'No change', 'Increase by 1', 'Reset to 0'], correctAnswer: 'Increase by 1', explanation: 'Every new land cell initially forms its own island, so the count increases by 1 before checking neighbors.' },
  { question: 'What happens to the island count when two neighboring land cells are merged?', options: ['It increases by 1', 'It decreases by 1', 'It doubles', 'It stays the same'], correctAnswer: 'It decreases by 1', explanation: 'When two previously separate islands are connected by a union operation, they become one island, so the count decreases by 1.' },
  { question: 'What should happen if the same cell position is added more than once?', options: ['Add it again and increment the count', 'Throw an error', 'Ignore the duplicate and keep the count unchanged', 'Reset the grid'], correctAnswer: 'Ignore the duplicate and keep the count unchanged', explanation: 'If a cell is already land, adding it again has no effect. We must check if the cell is already land before processing.' },
  { question: 'What is the time complexity of Number of Islands II with Union-Find (path compression + union by rank)?', options: ['O(k * m * n)', 'O(k * alpha(m*n))', 'O(m * n)', 'O(k^2)'], correctAnswer: 'O(k * alpha(m*n))', explanation: 'Each of the k operations performs a constant number of Union-Find operations, each costing O(alpha(m*n)) — practically constant.' },
  { question: 'What is the space complexity of Number of Islands II?', options: ['O(k)', 'O(m + n)', 'O(m * n)', 'O(k * m * n)'], correctAnswer: 'O(m * n)', explanation: 'We maintain parent, rank, and land arrays each of size m*n, giving O(m*n) space.' },
  { question: 'In how many directions do we check neighbors when adding a new land cell?', options: ['2', '3', '4', '8'], correctAnswer: '4', explanation: 'We check the four cardinal directions — up, down, left, right — for neighboring land cells to potentially merge islands.' },
  { question: 'If a 3x3 grid has operations [(0,0),(0,1),(1,2),(2,1),(1,1)], what is the island count after all operations?', options: ['5', '4', '3', '1'], correctAnswer: '1', explanation: 'After all five land cells are added and connected through (1,1) which bridges them all, they merge into a single island.' },
];
