export const countSmallerQuiz = [
  { question: 'In which direction should the array be traversed when using BIT for Count of Smaller Numbers After Self?', options: ['Left to right', 'Right to left', 'Both directions simultaneously', 'Random order'], correctAnswer: 'Right to left', explanation: 'Traversing right to left ensures that when we query the BIT for element at index i, only elements to the right of i have been inserted.' },
  { question: 'Why is coordinate compression needed in the BIT approach for this problem?', options: ['To sort the array', 'To map arbitrary or negative values to valid BIT indices', 'To reduce time complexity to O(1)', 'To avoid recursion'], correctAnswer: 'To map arbitrary or negative values to valid BIT indices', explanation: 'BIT indices must be positive integers in a bounded range. Coordinate compression maps all values to indices 1, 2, ..., n.' },
  { question: 'For element at compressed index k, which BIT query gives the count of smaller elements already inserted?', options: ['prefix_sum(k)', 'prefix_sum(k + 1)', 'prefix_sum(k - 1)', 'prefix_sum(n) - prefix_sum(k)'], correctAnswer: 'prefix_sum(k - 1)', explanation: 'prefix_sum(k - 1) sums frequencies of all elements with compressed index less than k, i.e., strictly smaller values.' },
  { question: 'What is the overall time complexity of the BIT approach for Count of Smaller Numbers After Self?', options: ['O(n)', 'O(n²)', 'O(n log n)', 'O(log n)'], correctAnswer: 'O(n log n)', explanation: 'Coordinate compression takes O(n log n) and each of the n BIT update/query operations takes O(log n), giving O(n log n) overall.' },
  { question: 'What is stored in the BIT during the traversal?', options: ['The actual values of elements', 'The frequency count of each compressed index', 'The prefix sums of the original array', 'The indices of sorted elements'], correctAnswer: 'The frequency count of each compressed index', explanation: 'Each time an element is processed, its compressed index is inserted into the BIT by adding 1 to that position.' },
  { question: 'What is the result for nums = [5, 2, 6, 1]?', options: ['[2, 1, 1, 0]', '[1, 1, 2, 0]', '[2, 1, 2, 0]', '[0, 1, 1, 2]'], correctAnswer: '[2, 1, 1, 0]', explanation: 'For 5: [2,1] are smaller → 2. For 2: [1] is smaller → 1. For 6: [1] is smaller → 1. For 1: nothing → 0.' },
  { question: 'After collecting results during right-to-left traversal, what must be done before returning?', options: ['Sort the result array', 'Reverse the result array', 'Remove duplicates', 'Apply prefix sum to result'], correctAnswer: 'Reverse the result array', explanation: 'Since elements are processed right to left, results are appended in reverse order and must be reversed before returning.' },
  { question: 'What is the brute force time complexity for Count of Smaller Numbers After Self?', options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(n³)'], correctAnswer: 'O(n²)', explanation: 'Brute force checks all pairs (i, j) where j > i, resulting in O(n²) comparisons.' },
  { question: 'Which of the following also solves Count of Smaller Numbers After Self in O(n log n)?', options: ['Quick Sort', 'Merge Sort with modification', 'Heap Sort', 'Bubble Sort'], correctAnswer: 'Merge Sort with modification', explanation: 'Modified merge sort counts inversions during the merge step, achieving O(n log n) — an alternative to the BIT approach.' },
  { question: 'What does the BIT query prefix_sum(n) return after all elements are inserted?', options: ['The maximum element', 'The total count of all inserted elements (n)', 'The sum of all original values', 'The number of distinct elements'], correctAnswer: 'The total count of all inserted elements (n)', explanation: 'Since each element adds 1 to its BIT position, prefix_sum(n) after all insertions equals n — the total number of elements.' },
];
