export const binarySearchQuiz = [
    { question: 'What is the prerequisite for binary search to work?', options: ['Array must be unsorted', 'Array must be sorted', 'Array must have even length', 'Array must contain only integers'], correctAnswer: 'Array must be sorted', explanation: 'Binary search requires a sorted array to correctly halve the search space.' },
    { question: 'What is the time complexity of binary search?', options: ['O(n)', 'O(n²)', 'O(log n)', 'O(1)'], correctAnswer: 'O(log n)', explanation: 'Binary search halves the search space each step — O(log n).' },
    { question: 'How does binary search find the middle element?', options: ['(low - high) / 2', '(low + high) / 2', 'low * high', 'high - low'], correctAnswer: '(low + high) / 2', explanation: 'Mid = (low + high) / 2 gives the middle index.' },
    { question: 'What happens when the middle element is greater than the target?', options: ['Search right half', 'Search left half', 'Return -1', 'Start over'], correctAnswer: 'Search left half', explanation: 'If mid > target, the target must be in the left half.' },
    { question: 'What is the space complexity of iterative binary search?', options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'], correctAnswer: 'O(1)', explanation: 'Iterative binary search uses constant extra space.' },
    { question: 'What is the space complexity of recursive binary search?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 'O(log n)', explanation: 'Recursive calls use O(log n) stack space.' },
    { question: 'Binary search is an example of which algorithm paradigm?', options: ['Greedy', 'Dynamic programming', 'Divide and conquer', 'Backtracking'], correctAnswer: 'Divide and conquer', explanation: 'Binary search divides the problem in half at each step.' },
    { question: 'What is the worst-case number of comparisons for binary search on n elements?', options: ['n', 'n/2', 'log₂(n) + 1', 'n²'], correctAnswer: 'log₂(n) + 1', explanation: 'At most ⌊log₂(n)⌋ + 1 comparisons are needed.' },
    { question: 'Which condition terminates binary search when element is not found?', options: ['low > high', 'low == high', 'mid == 0', 'high == 0'], correctAnswer: 'low > high', explanation: 'When low exceeds high, the search space is empty — element not found.' },
    { question: 'Binary search can be applied to which of these?', options: ['Unsorted linked list', 'Sorted array', 'Hash table', 'Graph'], correctAnswer: 'Sorted array', explanation: 'Binary search requires random access and sorted order — arrays fit best.' },
  ];