export const evaluateDivisionQuiz = [
  { question: 'What data structure is used in the Weighted Union-Find approach for Evaluate Division?', options: ['Stack', 'Queue', 'Disjoint Set Union with weights', 'Binary Search Tree'], correctAnswer: 'Disjoint Set Union with weights', explanation: 'Weighted Union-Find (DSU) stores a weight per node relative to its root to track ratios.' },
  { question: 'What does the weight of a node represent in Weighted Union-Find for Evaluate Division?', options: ['The depth of the node', 'The ratio of the node to its root', 'The number of children', 'The index of the node'], correctAnswer: 'The ratio of the node to its root', explanation: 'Each node stores weight[x] = x / root(x), enabling ratio computation between any two nodes in the same component.' },
  { question: 'Given A/B = 2 and B/C = 3, what is A/C?', options: ['5', '6', '1.5', '0.5'], correctAnswer: '6', explanation: 'A/C = (A/B) * (B/C) = 2 * 3 = 6.' },
  { question: 'What is returned for a query where one variable does not exist in any equation?', options: ['0.0', '1.0', '-1.0', 'Infinity'], correctAnswer: '-1.0', explanation: '-1.0 is returned when a variable is unknown (not present in the union-find structure).' },
  { question: 'What is the time complexity of building the Weighted Union-Find structure for N equations?', options: ['O(N²)', 'O(N log N)', 'O(N * alpha(N))', 'O(1)'], correctAnswer: 'O(N * alpha(N))', explanation: 'With path compression and union by rank, each operation is nearly O(1), giving O(N * alpha(N)) total.' },
  { question: 'What is the result of querying A/A if A exists in the equations?', options: ['-1.0', '0.0', '2.0', '1.0'], correctAnswer: '1.0', explanation: 'Any variable divided by itself is 1.0, as long as it exists in the structure.' },
  { question: 'What optimization technique reduces the path length in Union-Find during find()?', options: ['Union by rank', 'Path compression', 'Memoization', 'Lazy propagation'], correctAnswer: 'Path compression', explanation: 'Path compression flattens the tree during find(), making future queries faster.' },
  { question: 'In Weighted Union-Find, when union(x, y, value) is called, what relationship is established?', options: ['x + y = value', 'x - y = value', 'x / y = value', 'x * y = value'], correctAnswer: 'x / y = value', explanation: 'union(x, y, value) sets up the structure so that x / y = value can be derived from the weights.' },
  { question: 'What happens during path compression in Weighted Union-Find?', options: ['Only the parent pointer is updated', 'The weight is reset to 1', 'Both the parent pointer and the accumulated weight are updated', 'The node is deleted'], correctAnswer: 'Both the parent pointer and the accumulated weight are updated', explanation: 'During path compression, the weight of each node is multiplied along the path to correctly reflect the ratio to the new root.' },
  { question: 'Which of the following problems can be solved using the same Weighted Union-Find technique as Evaluate Division?', options: ['Finding shortest path in a graph', 'Unit conversion between measurement systems', 'Sorting an array', 'Finding a cycle in a directed graph'], correctAnswer: 'Unit conversion between measurement systems', explanation: 'Unit conversion involves chained ratios (e.g., km to miles via meters), which maps directly to the Weighted Union-Find approach.' },
];
