export const palindromePartitioningQuiz = [
    { question: 'What is the main goal of the Palindrome Partitioning (Minimum Cuts) problem?', options: ['Find the longest palindrome', 'Find the minimum number of cuts needed to partition a string into palindromic substrings', 'Count all substrings', 'Sort the characters of the string'], correctAnswer: 'Find the minimum number of cuts needed to partition a string into palindromic substrings', explanation: 'The goal is to divide the string into palindromic substrings using the minimum possible number of cuts.' },
    { question: 'What is a palindrome?', options: ['A string that contains only unique characters', 'A string that is sorted alphabetically', 'A string that reads the same forward and backward', 'A string with an even number of characters'], correctAnswer: 'A string that reads the same forward and backward', explanation: 'A palindrome remains unchanged when its characters are read from right to left.' },
    { question: 'How many cuts are required for the string "racecar"?', options: ['0', '1', '2', '3'], correctAnswer: '0', explanation: '"racecar" is already a palindrome, so no partitioning cuts are required.' },
    { question: 'What is the minimum number of cuts required for the string "aab"?', options: ['0', '1', '2', '3'], correctAnswer: '1', explanation: 'The string can be partitioned as "aa|b", where both parts are palindromes, requiring one cut.' },
    { question: 'Which dynamic programming table is commonly used to determine whether a substring is a palindrome?', options: ['visited[i][j]', 'pal[i][j]', 'cost[i][j]', 'path[i][j]'], correctAnswer: 'pal[i][j]', explanation: 'The pal[i][j] table stores whether the substring from index i to j is a palindrome.' },
    { question: 'What is the recurrence condition for a substring s[i...j] to be a palindrome?', options: ['s[i] == s[j] and the inner substring is a palindrome', 's[i] != s[j]', 's[i] > s[j]', 'Only the first character must match'], correctAnswer: 's[i] == s[j] and the inner substring is a palindrome', explanation: 'A substring is a palindrome when its boundary characters match and the substring between them is also a palindrome.' },
    { question: 'What is the typical time complexity of the standard dynamic programming solution for minimum palindrome partitioning cuts?', options: ['O(1)', 'O(log n)', 'O(n²)', 'O(2ⁿ)'], correctAnswer: 'O(n²)', explanation: 'The palindrome table and minimum-cut DP can both be computed in O(n²) time.' },
    { question: 'What is the auxiliary space complexity of storing the complete palindrome table for a string of length n?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 'O(n²)', explanation: 'The palindrome table contains an entry for every pair of substring boundaries, requiring O(n²) space.' },
    { question: 'For the string "abba", what is the minimum number of cuts?', options: ['0', '1', '2', '3'], correctAnswer: '0', explanation: '"abba" itself is a palindrome, so it can be kept as a single partition without making any cuts.' },
    { question: 'Why is dynamic programming useful for Palindrome Partitioning?', options: ['It randomly selects partition points', 'It avoids recomputing palindrome and minimum-cut subproblems', 'It sorts the string before processing', 'It removes all duplicate characters'], correctAnswer: 'It avoids recomputing palindrome and minimum-cut subproblems', explanation: 'Dynamic programming stores previously computed palindrome states and minimum partition costs so overlapping subproblems do not have to be solved repeatedly.' },
];