export const kthSmallestElementQuiz = [
  { question: 'What does the BIT store in the Kth Smallest Element using Order Statistics approach?', options: ['The actual values of elements', 'The frequency count of each compressed value', 'The prefix sums of the original array', 'The sorted order of elements'], correctAnswer: 'The frequency count of each compressed value', explanation: 'The BIT acts as a frequency table where each index stores how many times the corresponding (compressed) value has been inserted.' },
  { question: 'What is the time complexity of inserting an element into the BIT for order statistics?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctAnswer: 'O(log n)', explanation: 'A BIT update traverses at most O(log n) indices by repeatedly adding the lowest set bit.' },
  { question: 'What condition is checked during binary search on BIT prefix sums to find the Kth smallest element?', options: ['prefix_sum(i) == k', 'prefix_sum(i) >= k', 'prefix_sum(i) <= k', 'prefix_sum(i) > k + 1'], correctAnswer: 'prefix_sum(i) >= k', explanation: 'We find the smallest index i such that prefix_sum(i) >= k, meaning at least k elements have values <= the value at index i.' },
  { question: 'What is the time complexity of finding the Kth smallest using binary search on BIT prefix sums?', options: ['O(log n)', 'O(log² n)', 'O(n)', 'O(n log n)'], correctAnswer: 'O(log² n)', explanation: 'Binary search runs O(log n) iterations, and each prefix_sum call takes O(log n), giving O(log² n) overall.' },
  { question: 'What optimization reduces the Kth smallest query from O(log² n) to O(log n)?', options: ['Path compression', 'Coordinate compression', 'Binary lifting on the BIT', 'Lazy propagation'], correctAnswer: 'Binary lifting on the BIT', explanation: 'Binary lifting descends the BIT tree bit by bit from the highest power of 2, finding the Kth position in a single O(log n) pass.' },
  { question: 'Why is coordinate compression necessary in the BIT-based Kth smallest approach?', options: ['To sort the elements', 'To map arbitrary or large values to a bounded BIT index range', 'To remove duplicates', 'To speed up the prefix sum computation'], correctAnswer: 'To map arbitrary or large values to a bounded BIT index range', explanation: 'BIT indices must be positive integers in a bounded range. Coordinate compression maps all values to 1, 2, ..., m before insertion.' },
  { question: 'Given elements [3, 1, 2, 5, 4] inserted into the BIT, what is the 3rd smallest element?', options: ['1', '2', '3', '4'], correctAnswer: '3', explanation: 'Sorted order is [1, 2, 3, 4, 5]. The 3rd smallest is 3.' },
  { question: 'What happens to the BIT frequency count when a duplicate value is inserted?', options: ['It is ignored', 'The count at that index is incremented by 1', 'The count is reset to 1', 'A new index is created'], correctAnswer: 'The count at that index is incremented by 1', explanation: 'Duplicates are handled naturally — each insertion adds 1 to the BIT at the compressed index, so the frequency count increases correctly.' },
  { question: 'Which data structure can also solve Kth smallest with dynamic insertions but is more complex to implement?', options: ['Stack', 'Queue', 'Balanced BST (Order Statistics Tree)', 'Hash Map'], correctAnswer: 'Balanced BST (Order Statistics Tree)', explanation: 'A balanced BST augmented with subtree sizes (order statistics tree) supports O(log n) insert and Kth smallest, but is significantly harder to implement than a BIT.' },
  { question: 'What is the space complexity of the BIT used for Kth Smallest Element order statistics?', options: ['O(log n)', 'O(n²)', 'O(n)', 'O(4n)'], correctAnswer: 'O(n)', explanation: 'The BIT array has size m+1 where m is the number of distinct compressed values, which is at most n, giving O(n) space.' },
];
