export const rangeSumQueryMutableQuiz = [
  { question: 'What does BIT stand for in the context of Range Sum Query?', options: ['Binary Indexed Tree', 'Balanced Interval Tree', 'Binary Insertion Tree', 'Bit Interval Table'], correctAnswer: 'Binary Indexed Tree', explanation: 'BIT stands for Binary Indexed Tree, also known as a Fenwick Tree, used for efficient prefix sum queries and updates.' },
  { question: 'What bitwise operation is used to find the lowest set bit in a Fenwick Tree?', options: ['i | (-i)', 'i & (-i)', 'i ^ (-i)', 'i >> 1'], correctAnswer: 'i & (-i)', explanation: 'i & (-i) isolates the lowest set bit of i, which determines the range each BIT index is responsible for.' },
  { question: 'What is the time complexity of a point update in a Fenwick Tree?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctAnswer: 'O(log n)', explanation: 'A point update traverses at most O(log n) indices by repeatedly adding the lowest set bit.' },
  { question: 'What is the time complexity of a prefix sum query in a Fenwick Tree?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctAnswer: 'O(log n)', explanation: 'A prefix sum query traverses at most O(log n) indices by repeatedly subtracting the lowest set bit.' },
  { question: 'How is a range sum query [l, r] computed using a Fenwick Tree?', options: ['prefix(r) + prefix(l)', 'prefix(r) - prefix(l)', 'prefix(r) - prefix(l - 1)', 'prefix(r + 1) - prefix(l)'], correctAnswer: 'prefix(r) - prefix(l - 1)', explanation: 'Range sum [l, r] = prefix_sum(r) - prefix_sum(l - 1), using the prefix sum property.' },
  { question: 'What indexing convention does a Fenwick Tree use?', options: ['0-based indexing', '1-based indexing', 'Both 0 and 1 based', 'Negative indexing'], correctAnswer: '1-based indexing', explanation: 'Fenwick Trees use 1-based indexing because the lowest set bit of 0 is undefined, causing infinite loops.' },
  { question: 'During a point update at index i, what is the next index to update?', options: ['i - (i & -i)', 'i + (i & -i)', 'i * 2', 'i / 2'], correctAnswer: 'i + (i & -i)', explanation: 'Adding the lowest set bit moves to the next index responsible for a larger range during an update.' },
  { question: 'During a prefix sum query at index i, what is the next index to visit?', options: ['i + (i & -i)', 'i - (i & -i)', 'i * 2', 'i - 1'], correctAnswer: 'i - (i & -i)', explanation: 'Subtracting the lowest set bit moves to the parent index, accumulating the prefix sum.' },
  { question: 'Which data structure is simpler to implement but less flexible than a Segment Tree for range queries?', options: ['AVL Tree', 'Sparse Table', 'Fenwick Tree', 'Heap'], correctAnswer: 'Fenwick Tree', explanation: 'Fenwick Tree is simpler and more cache-friendly than a Segment Tree but only natively supports sum queries, not min/max.' },
  { question: 'What is the space complexity of a Fenwick Tree for an array of size n?', options: ['O(n log n)', 'O(4n)', 'O(n)', 'O(log n)'], correctAnswer: 'O(n)', explanation: 'A Fenwick Tree uses exactly n+1 elements (1-indexed), giving O(n) space complexity.' },
];
