export const topKFrequentQuiz = [
  { question: 'What data structure is most commonly used to efficiently solve the Top K Frequent Elements problem?', options: ['Queue', 'Stack', 'Heap (Priority Queue)', 'Linked List'], correctAnswer: 'Heap (Priority Queue)', explanation: 'A Heap (Priority Queue) efficiently keeps track of the most frequent elements.' },
  { question: 'Which data structure is typically used to count the frequency of elements?', options: ['Hash Map', 'Stack', 'Queue', 'Tree'], correctAnswer: 'Hash Map', explanation: 'A Hash Map stores each element along with its frequency.' },
  { question: 'What does the value K represent in the Top K Frequent Elements problem?', options: ['Size of the array', 'Number of unique elements', 'Number of most frequent elements to return', 'Maximum frequency'], correctAnswer: 'Number of most frequent elements to return', explanation: 'K specifies how many of the most frequent elements should be returned.' },
  { question: 'What is the first step in solving the Top K Frequent Elements problem?', options: ['Sort the array', 'Build a Heap', 'Count the frequency of each element', 'Reverse the array'], correctAnswer: 'Count the frequency of each element', explanation: 'Frequency counting is performed before using a heap.' },
  { question: 'Which Heap is commonly used to extract the most frequent elements directly?', options: ['Min Heap', 'Max Heap', 'Binary Search Tree', 'Deque'], correctAnswer: 'Max Heap', explanation: 'A Max Heap always removes the element with the highest frequency first.' },
  { question: 'Which Heap provides the optimal O(n log k) solution?', options: ['Max Heap', 'Min Heap of size K', 'Binary Heap', 'Fibonacci Heap'], correctAnswer: 'Min Heap of size K', explanation: 'Maintaining a Min Heap of size K keeps only the K most frequent elements.' },
  { question: 'What is the average time complexity of the Heap-based Top K Frequent Elements algorithm?', options: ['O(n²)', 'O(log n)', 'O(n log k)', 'O(n³)'], correctAnswer: 'O(n log k)', explanation: 'Frequency counting takes O(n) and heap operations take O(n log k).' },
  { question: 'Which algorithmic concept is primarily used along with Heap in this problem?', options: ['Recursion', 'Frequency Counting', 'Binary Search', 'Backtracking'], correctAnswer: 'Frequency Counting', explanation: 'The frequency of each element must be computed before building the heap.' },
  { question: 'What is stored inside the Heap for this problem?', options: ['Only the elements', 'Only the frequencies', 'Element-frequency pairs', 'Array indices'], correctAnswer: 'Element-frequency pairs', explanation: 'Each heap node stores both the element and its frequency.' },
  { question: 'Which real-world application commonly uses the Top K Frequent Elements algorithm?', options: ['CPU Scheduling', 'Recommendation Systems', 'Graph Traversal', 'Memory Allocation'], correctAnswer: 'Recommendation Systems', explanation: 'Recommendation systems often identify the most frequently occurring or most popular items using this technique.' }
];