export const numberOfProvincesQuiz = [
  { question: 'What does a "province" represent in the Number of Provinces problem?', options: ['A single city', 'A group of directly or indirectly connected cities', 'A city with no connections', 'The largest city in the graph'], correctAnswer: 'A group of directly or indirectly connected cities', explanation: 'A province is a connected component — a set of cities that can reach each other directly or indirectly.' },
  { question: 'What data structure represents the input in the Number of Provinces problem?', options: ['Adjacency list', 'Adjacency matrix', 'Edge list', 'Incidence matrix'], correctAnswer: 'Adjacency matrix', explanation: 'The input isConnected is an n x n adjacency matrix where isConnected[i][j] = 1 means cities i and j are directly connected.' },
  { question: 'What is the time complexity of solving Number of Provinces using DFS on an adjacency matrix?', options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(n^3)'], correctAnswer: 'O(n^2)', explanation: 'We potentially visit every cell of the n x n adjacency matrix, giving O(n^2) time complexity.' },
  { question: 'What is the space complexity of the DFS approach for Number of Provinces?', options: ['O(1)', 'O(n)', 'O(n^2)', 'O(log n)'], correctAnswer: 'O(n)', explanation: 'We use a visited array of size n and the recursion stack can go up to depth n in the worst case.' },
  { question: 'If isConnected = [[1,1,0],[1,1,0],[0,0,1]], how many provinces are there?', options: ['1', '2', '3', '0'], correctAnswer: '2', explanation: 'Cities 0 and 1 are connected forming one province, and city 2 is isolated forming another province.' },
  { question: 'Which algorithm can also be used to solve Number of Provinces efficiently?', options: ['Binary Search', 'Union-Find (Disjoint Set Union)', 'Merge Sort', 'Dijkstra'], correctAnswer: 'Union-Find (Disjoint Set Union)', explanation: 'Union-Find efficiently groups connected nodes and counts the number of distinct sets, which equals the number of provinces.' },
  { question: 'What does isConnected[i][i] always equal in this problem?', options: ['0', '1', '-1', 'Undefined'], correctAnswer: '1', explanation: 'Every city is connected to itself, so the diagonal of the adjacency matrix is always 1.' },
  { question: 'What happens when DFS is called on an already visited node?', options: ['It starts a new province', 'It is skipped', 'It resets the visited array', 'It throws an error'], correctAnswer: 'It is skipped', explanation: 'We check the visited array before starting DFS. If a node is already visited, we skip it to avoid revisiting.' },
  { question: 'If all n cities are connected to each other, how many provinces are there?', options: ['n', 'n-1', '0', '1'], correctAnswer: '1', explanation: 'If all cities are connected, they form a single connected component, which is one province.' },
  { question: 'If no two cities are connected (only self-loops), how many provinces are there?', options: ['0', '1', 'n', 'n/2'], correctAnswer: 'n', explanation: 'If no city is connected to any other city, each city forms its own province, giving n provinces total.' },
];
