export const subarrayXORQuiz = [
  { question: 'Which technique is most commonly used to solve "Subarray with XOR Equal to K" optimally?', options: ['Sliding Window', 'Prefix XOR + Hash Map', 'Two Pointers', 'Sorting'], correctAnswer: 'Prefix XOR + Hash Map', explanation: 'The optimal solution uses Prefix XOR along with a Hash Map to efficiently count valid subarrays.' },
  { question: 'What is the time complexity of the optimal Prefix XOR solution?', options: ['O(n²)', 'O(log n)', 'O(n)', 'O(n log n)'], correctAnswer: 'O(n)', explanation: 'Each element is processed exactly once while updating the Prefix XOR and Hash Map.' },
  { question: 'What is the space complexity of the optimal Prefix XOR approach?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 'O(n)', explanation: 'The Hash Map may store up to n different prefix XOR values.' },
  { question: 'What operation is used to compute the running Prefix XOR?', options: ['Addition (+)', 'Bitwise OR (|)', 'Bitwise XOR (^)', 'Bitwise AND (&)'], correctAnswer: 'Bitwise XOR (^)', explanation: 'Prefix XOR is obtained by repeatedly applying the XOR operator.' },
  { question: 'If prefixXOR is the XOR from index 0 to i, what value must have appeared earlier to form a subarray XOR equal to K?', options: ['prefixXOR + K', 'prefixXOR ^ K', 'prefixXOR - K', 'K ^ 0'], correctAnswer: 'prefixXOR ^ K', explanation: 'If previousPrefix ^ currentPrefix = K, then previousPrefix = currentPrefix ^ K.' },
  { question: 'Why is the Hash Map initialized with {0 : 1}?', options: ['To reduce memory usage', 'To handle subarrays starting from index 0', 'To sort the array', 'To avoid overflow'], correctAnswer: 'To handle subarrays starting from index 0', explanation: 'A Prefix XOR of 0 before the array begins allows subarrays starting at index 0 to be counted.' },
  { question: 'Which property of XOR makes the Prefix XOR technique work?', options: ['a ^ a = 1', 'a ^ 0 = 1', 'a ^ a = 0', 'a ^ b = a + b'], correctAnswer: 'a ^ a = 0', explanation: 'Since x ^ x = 0, common prefix XOR values cancel out to isolate the subarray XOR.' },
  { question: 'Which data structure is used to store Prefix XOR frequencies?', options: ['Queue', 'Stack', 'Hash Map', 'Heap'], correctAnswer: 'Hash Map', explanation: 'A Hash Map efficiently stores and retrieves the frequency of each Prefix XOR.' },
  { question: 'Why is the Sliding Window technique generally not suitable for this problem?', options: ['XOR is not monotonic', 'Arrays are unsorted', 'Sliding Window only works for strings', 'XOR cannot be computed incrementally'], correctAnswer: 'XOR is not monotonic', explanation: 'Unlike sums, XOR does not increase or decrease predictably when expanding or shrinking the window.' },
  { question: 'What should be done after processing each Prefix XOR?', options: ['Clear the Hash Map', 'Store or update its frequency in the Hash Map', 'Sort the Prefix XOR values', 'Reset Prefix XOR to 0'], correctAnswer: 'Store or update its frequency in the Hash Map', explanation: 'Updating the frequency ensures future Prefix XOR values can correctly count matching subarrays.' },
];