export const travelingSalesmanBitmaskQuiz = [
    { question: 'What does the bitmask represent in the Traveling Salesman Problem?', options: ['The travel cost between cities', 'The set of cities already visited', 'The number of available vehicles', 'The starting city only'], correctAnswer: 'The set of cities already visited', explanation: 'Each bit in the mask represents whether a particular city has already been visited.' },
    { question: 'What is the main purpose of dynamic programming in the bitmask TSP solution?', options: ['To sort the cities', 'To store minimum costs for visited-city states', 'To remove duplicate cities', 'To generate random routes'], correctAnswer: 'To store minimum costs for visited-city states', explanation: 'DP stores the minimum cost of reaching a city with a particular set of visited cities.' },
    { question: 'What does dp[mask][u] represent in the bitmask TSP algorithm?', options: ['The number of cities in mask', 'The cost of returning directly to the starting city', 'The minimum cost to reach city u after visiting the cities in mask', 'The maximum cost of visiting city u'], correctAnswer: 'The minimum cost to reach city u after visiting the cities in mask', explanation: 'dp[mask][u] stores the minimum travel cost for reaching city u after visiting exactly the cities represented by mask.' },
    { question: 'Why is the starting city marked as visited initially in the bitmask TSP algorithm?', options: ['To exclude it from the input', 'To indicate that the tour begins there', 'To reduce the number of cities', 'To calculate the average travel cost'], correctAnswer: 'To indicate that the tour begins there', explanation: 'The initial state marks the starting city as visited and gives it a travel cost of zero.' },
    { question: 'What is the time complexity of the standard bitmask DP solution for TSP with n cities?', options: ['O(n)', 'O(n²)', 'O(n² × 2ⁿ)', 'O(2ⁿ)'], correctAnswer: 'O(n² × 2ⁿ)', explanation: 'There are 2ⁿ possible masks, n possible current cities, and up to n transitions from each state.' },
    { question: 'What is the space complexity of the standard bitmask DP solution for TSP?', options: ['O(n)', 'O(2ⁿ)', 'O(n × 2ⁿ)', 'O(n²)'], correctAnswer: 'O(n × 2ⁿ)', explanation: 'The DP table contains 2ⁿ masks and n possible ending cities, requiring O(n × 2ⁿ) space.' },
    { question: 'When can a city v be added to the current TSP state represented by mask?', options: ['When v is already visited', 'When v has the highest cost', 'When the bit for v is not set in mask', 'When v is the starting city only'], correctAnswer: 'When the bit for v is not set in mask', explanation: 'A city can be visited next only if its corresponding bit is not already set in the visited mask.' },
    { question: 'After all cities have been visited, what final step is required to complete the TSP tour?', options: ['Sort all visited cities', 'Return from the last city to the starting city', 'Clear the bitmask', 'Visit every city again'], correctAnswer: 'Return from the last city to the starting city', explanation: 'A Hamiltonian tour must return to the starting city after visiting every city.' },
    { question: 'What is the full mask when there are n cities?', options: ['0', 'n', '2ⁿ', '2ⁿ - 1'], correctAnswer: '2ⁿ - 1', explanation: 'A mask with all n bits set has the binary value 2ⁿ - 1 and represents that every city has been visited.' },
    { question: 'Which algorithmic technique is primarily used to make the TSP solution feasible for a small number of cities?', options: ['Bitmasking with dynamic programming', 'Binary search with recursion', 'Greedy sorting', 'Breadth-first search'], correctAnswer: 'Bitmasking with dynamic programming', explanation: 'Bitmasking represents visited subsets compactly while dynamic programming avoids recomputing the same states.' },
];