export const partitionEqualSubsetSumQuiz = [
    { question: 'What is the main objective of the Partition Equal Subset Sum problem?', options: ['Find the largest subset in an array', 'Determine whether an array can be divided into two subsets with equal sums', 'Find the subset with the minimum sum', 'Sort the array into two equal parts'], correctAnswer: 'Determine whether an array can be divided into two subsets with equal sums', explanation: 'The objective is to determine whether the given array can be partitioned into two subsets whose sums are equal.' },
    { question: 'What condition immediately makes equal partitioning impossible?', options: ['The array contains duplicate values', 'The array is not sorted', 'The total sum of the array is odd', 'The array contains more than five elements'], correctAnswer: 'The total sum of the array is odd', explanation: 'If the total sum is odd, it cannot be divided into two equal integer subset sums.' },
    { question: 'If the total sum of an array is 20, what target subset sum must be formed?', options: ['5', '10', '15', '20'], correctAnswer: '10', explanation: 'For an even total sum, the target subset sum is half of the total sum, so 20 / 2 = 10.' },
    { question: 'Which technique is commonly used to solve Partition Equal Subset Sum efficiently?', options: ['Binary Search', 'Dynamic Programming', 'Breadth First Search', 'Merge Sort'], correctAnswer: 'Dynamic Programming', explanation: 'The problem can be reduced to a subset sum problem and efficiently solved using dynamic programming.' },
    { question: 'What does dp[s] represent in the one-dimensional dynamic programming solution?', options: ['Whether a subset can form sum s', 'The number of elements equal to s', 'The maximum element with value s', 'The index of the element producing sum s'], correctAnswer: 'Whether a subset can form sum s', explanation: 'dp[s] indicates whether some subset of the processed elements can form the sum s.' },
    { question: 'Why is the DP array updated from target down to the current number?', options: ['To sort the DP array', 'To ensure each element is used at most once', 'To remove duplicate elements', 'To calculate the total sum'], correctAnswer: 'To ensure each element is used at most once', explanation: 'Updating the DP array from right to left prevents the current element from being reused multiple times.' },
    { question: 'What is the result for the array [1, 5, 11, 5]?', options: ['true', 'false', '0', 'Cannot be determined'], correctAnswer: 'true', explanation: 'The total sum is 22 and the target is 11. The subset [11] forms the target, while [1, 5, 5] forms the other 11.' },
    { question: 'What is the result for the array [1, 2, 3, 5]?', options: ['true', 'false', '0', 'Cannot be determined'], correctAnswer: 'false', explanation: 'The total sum is 11, which is odd, so the array cannot be divided into two subsets with equal sums.' },
    { question: 'What is the time complexity of the one-dimensional DP solution, where n is the number of elements and S is the total sum?', options: ['O(n)', 'O(S)', 'O(n × S)', 'O(n²)'], correctAnswer: 'O(n × S)', explanation: 'Each of the n elements can update DP states up to the target sum, resulting in O(n × S) time complexity.' },
    { question: 'What is the space complexity of the optimized one-dimensional DP solution?', options: ['O(1)', 'O(n)', 'O(S)', 'O(n × S)'], correctAnswer: 'O(S)', explanation: 'The optimized solution uses a one-dimensional DP array based on the target sum, giving O(S) space complexity.' },
];