export const rangeMinimumQueryQuiz = [
  { question: 'What does a Segment Tree node store in the Range Minimum Query problem?', options: ['The sum of its segment', 'The maximum of its segment', 'The minimum of its segment', 'The index of its segment'], correctAnswer: 'The minimum of its segment', explanation: 'In RMQ using a Segment Tree, each node stores the minimum value of the array segment it represents.' },
  { question: 'What is the time complexity of building a Segment Tree on an array of size n?', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'], correctAnswer: 'O(n)', explanation: 'Building the Segment Tree visits each node once, and there are 2n - 1 nodes, so the build time is O(n).' },
  { question: 'What is the time complexity of a range minimum query on a Segment Tree?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctAnswer: 'O(log n)', explanation: 'A query traverses at most O(log n) nodes because the tree height is log n.' },
  { question: 'What is the time complexity of a point update on a Segment Tree?', options: ['O(1)', 'O(n)', 'O(log n)', 'O(n log n)'], correctAnswer: 'O(log n)', explanation: 'A point update modifies the leaf and propagates changes up through O(log n) ancestors.' },
  { question: 'How much space does a Segment Tree typically require for an array of size n?', options: ['O(n)', 'O(2n)', 'O(4n)', 'O(n²)'], correctAnswer: 'O(4n)', explanation: 'To safely store all nodes including leaves and internal nodes, 4*n space is allocated for the segment tree array.' },
  { question: 'What value should be returned for a query on a segment completely outside the query range [l, r]?', options: ['0', '-1', 'Negative infinity', 'Positive infinity'], correctAnswer: 'Positive infinity', explanation: 'Returning positive infinity (INT_MAX) for out-of-range segments ensures it does not affect the minimum computation.' },
  { question: 'Which alternative data structure supports O(1) range minimum queries but does NOT support updates?', options: ['Segment Tree', 'Fenwick Tree', 'Sparse Table', 'AVL Tree'], correctAnswer: 'Sparse Table', explanation: 'Sparse Table answers RMQ in O(1) using precomputed powers of 2, but it is static and cannot handle updates.' },
  { question: 'In a Segment Tree stored as an array, what are the children of node at index i?', options: ['2i and 2i+2', '2i+1 and 2i+2', '2i and 2i+1', 'i/2 and i/2+1'], correctAnswer: '2i and 2i+1', explanation: 'For a 1-indexed segment tree array, the left child of node i is at 2i and the right child is at 2i+1.' },
  { question: 'What is the height of a Segment Tree built on an array of size n?', options: ['n', 'n/2', 'log₂(n)', 'log₂(n) + 1'], correctAnswer: 'log₂(n)', explanation: 'The Segment Tree is a balanced binary tree with height ⌈log₂(n)⌉.' },
  { question: 'Which of the following problems is best solved using a Segment Tree over a Sparse Table?', options: ['Static RMQ with no updates', 'RMQ with frequent point updates', 'Finding median in a range', 'Sorting an array'], correctAnswer: 'RMQ with frequent point updates', explanation: 'Segment Tree supports O(log n) updates, making it the right choice when the array changes dynamically.' },
];
