export const groupAnagramsQuiz = [
    { question: 'What is the main idea behind the Group Anagrams problem?', options: ['Sort the array', 'Group words with the same characters', 'Find duplicate words', 'Reverse every string'], correctAnswer: 'Group words with the same characters', explanation: 'Anagrams contain the same characters with the same frequencies, so they belong in the same group.' },
    { question: 'What is the most common key used to group anagrams?', options: ['Word length', 'Sorted characters of the word', 'ASCII sum', 'First character'], correctAnswer: 'Sorted characters of the word', explanation: 'Sorting the characters produces the same key for all anagrams.' },
    { question: 'Which data structure is typically used to group anagrams efficiently?', options: ['Stack', 'Queue', 'Hash Map', 'Heap'], correctAnswer: 'Hash Map', explanation: 'A hash map stores the signature of each word and its corresponding group.' },
    { question: 'Which pair of words are anagrams?', options: ['cat & act', 'dog & dig', 'bat & tabo', 'code & coder'], correctAnswer: 'cat & act', explanation: 'Both words contain the same letters with the same frequencies.' },
    { question: 'What is the time complexity of grouping anagrams using sorted strings as keys?', options: ['O(n)', 'O(n²)', 'O(n × k log k)', 'O(log n)'], correctAnswer: 'O(n × k log k)', explanation: 'Sorting each word of length k takes O(k log k), repeated for n words.' },
    { question: 'How can the sorting step be avoided for lowercase English letters?', options: ['Binary Search', 'Trie', 'Frequency Count', 'Heap Sort'], correctAnswer: 'Frequency Count', explanation: 'A frequency array of 26 letters can be used as the hash key instead of sorting.' },
    { question: 'What is the time complexity when using a frequency-count signature?', options: ['O(n × k)', 'O(n²)', 'O(k²)', 'O(log n)'], correctAnswer: 'O(n × k)', explanation: 'Each character is processed once to build the frequency signature.' },
    { question: 'Why do anagrams generate the same sorted-string key?', options: ['They have the same length only', 'They contain identical characters in different orders', 'They start with the same letter', 'They end with the same letter'], correctAnswer: 'They contain identical characters in different orders', explanation: 'Sorting rearranges all anagrams into the exact same character sequence.' },
    { question: 'What is the primary space complexity of the Group Anagrams algorithm?', options: ['O(1)', 'O(log n)', 'O(n × k)', 'O(k)'], correctAnswer: 'O(n × k)', explanation: 'The hash map stores all words and their grouping information.' },
    { question: 'Which algorithmic concept is most important for solving Group Anagrams efficiently?', options: ['Hashing', 'Greedy', 'Dynamic Programming', 'Binary Search'], correctAnswer: 'Hashing', explanation: 'Hashing enables fast lookup and grouping of words sharing the same signature.' },
];