export const twoSumQuiz = [
  { question: 'What is the optimal data structure used to solve the classic Two Sum problem in O(n) time?', options: ['Stack', 'Queue', 'Hash Map', 'Heap'], correctAnswer: 'Hash Map', explanation: 'A Hash Map stores previously seen numbers for constant-time lookup.' },
  { question: 'What is the time complexity of the optimal Two Sum solution using a Hash Map?', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(log n)'], correctAnswer: 'O(n)', explanation: 'Each element is processed once, and Hash Map operations take O(1) on average.' },
  { question: 'What is the space complexity of the optimal Hash Map approach?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], correctAnswer: 'O(n)', explanation: 'In the worst case, all elements are stored in the Hash Map.' },
  { question: 'While traversing the array, what value do we look for in the Hash Map?', options: ['Current element', 'Current index', 'target - current element', 'Current element + target'], correctAnswer: 'target - current element', explanation: 'If the complement already exists, we have found a valid pair.' },
  { question: 'What does the Hash Map typically store in the classic Two Sum solution?', options: ['Element frequencies', 'Element value as key and its index as value', 'Only indices', 'Sorted elements'], correctAnswer: 'Element value as key and its index as value', explanation: 'The value is used as the key and its index is stored as the corresponding value.' },
  { question: 'If the complement is found in the Hash Map, what should the algorithm return?', options: ['The two values', 'The two indices', 'The target value', 'The array length'], correctAnswer: 'The two indices', explanation: 'The classic Two Sum problem requires returning the indices of the two numbers.' },
  { question: 'Why is a brute-force Two Sum solution slower?', options: ['It uses recursion', 'It checks every possible pair', 'It requires sorting', 'It uses extra memory'], correctAnswer: 'It checks every possible pair', explanation: 'Nested loops compare every pair, resulting in O(n²) time complexity.' },
  { question: 'Which approach is commonly used for Two Sum in a sorted array?', options: ['Breadth First Search', 'Two Pointers', 'Dynamic Programming', 'Binary Search Tree'], correctAnswer: 'Two Pointers', explanation: 'For sorted arrays, two pointers efficiently find the target sum in O(n).' },
  { question: 'What happens if no two numbers add up to the target?', options: ['Return -1', 'Return null', 'Return an empty array', 'Return the target'], correctAnswer: 'Return an empty array', explanation: 'The standard implementation returns an empty array when no valid pair exists.' },
  { question: 'Which algorithmic technique is primarily used in the optimal Two Sum solution?', options: ['Greedy', 'Hashing', 'Backtracking', 'Divide and Conquer'], correctAnswer: 'Hashing', explanation: 'Hashing enables constant-time complement lookup, reducing the time complexity to O(n).' },
];