export const kthLargestElementQuiz = [
  { question: 'Which data structure is commonly used to efficiently find the kth largest element?', options: ['Stack', 'Queue', 'Min Heap', 'Linked List'], correctAnswer: 'Min Heap', explanation: 'A Min Heap of size k efficiently maintains the k largest elements seen so far.' },
  { question: 'What should be the size of the Min Heap while finding the kth largest element?', options: ['1', 'n', 'k', 'k + 1'], correctAnswer: 'k', explanation: 'The Min Heap is maintained with exactly k elements throughout the algorithm.' },
  { question: 'What does the root of the Min Heap represent after processing all elements?', options: ['Largest element', 'Smallest element', 'Median element', 'Kth largest element'], correctAnswer: 'Kth largest element', explanation: 'The root of the Min Heap stores the kth largest element after all insertions.' },
  { question: 'What should happen if the current element is larger than the root of the Min Heap?', options: ['Ignore the element', 'Replace the root and heapify', 'Clear the heap', 'Insert without removing'], correctAnswer: 'Replace the root and heapify', explanation: 'A larger element belongs among the top k elements, so it replaces the root.' },
  { question: 'What happens if the current element is smaller than or equal to the root of the Min Heap?', options: ['Replace the root', 'Insert into heap', 'Ignore the element', 'Sort the heap'], correctAnswer: 'Ignore the element', explanation: 'It cannot be among the top k largest elements, so it is ignored.' },
  { question: 'What is the overall time complexity of the Min Heap approach?', options: ['O(n²)', 'O(n log n)', 'O(n log k)', 'O(k²)'], correctAnswer: 'O(n log k)', explanation: 'Each heap operation takes O(log k) and is performed for up to n elements.' },
  { question: 'What is the space complexity of the Min Heap solution?', options: ['O(1)', 'O(log n)', 'O(k)', 'O(n)'], correctAnswer: 'O(k)', explanation: 'Only k elements are stored in the Min Heap at any time.' },
  { question: 'Which of the following is true about the input array?', options: ['It must be sorted', 'It must contain distinct elements', 'It may be unsorted', 'It must be in descending order'], correctAnswer: 'It may be unsorted', explanation: 'The Min Heap approach works even if the array is completely unsorted.' },
  { question: 'If k = 1, what does the algorithm return?', options: ['Smallest element', 'Median element', 'Largest element', 'Second largest element'], correctAnswer: 'Largest element', explanation: 'The 1st largest element is simply the maximum element in the array.' },
  { question: 'Why is the Min Heap preferred over sorting the entire array?', options: ['It uses recursion', 'It avoids processing all elements', 'It maintains only the top k largest elements', 'It requires a sorted array'], correctAnswer: 'It maintains only the top k largest elements', explanation: 'Maintaining only k elements is more efficient than sorting the complete array when k is small.' }
];