export const accountsMergeQuiz = [
  { question: 'What determines that two accounts belong to the same person in the Accounts Merge problem?', options: ['They have the same account name', 'They share at least one common email address', 'They have the same number of emails', 'They appear consecutively in the input'], correctAnswer: 'They share at least one common email address', explanation: 'Two accounts belong to the same person if and only if they share at least one common email address, regardless of the account name.' },
  { question: 'In the Union-Find approach for Accounts Merge, what is used as the representative node for each account during union operations?', options: ['The account name', 'The last email in the account', 'The first email in the account', 'A randomly chosen email'], correctAnswer: 'The first email in the account', explanation: 'All emails in an account are unioned with the first email, making it the representative. This ensures all emails in the same account are connected.' },
  { question: 'After all union operations are complete, how are merged accounts reconstructed?', options: ['By sorting all emails globally', 'By grouping emails that share the same root in Union-Find, sorting them, and prepending the name', 'By reversing the input order', 'By removing duplicate emails from each account'], correctAnswer: 'By grouping emails that share the same root in Union-Find, sorting them, and prepending the name', explanation: 'Emails with the same root belong to the same person. They are collected, sorted, and the account name is prepended to form the final merged account.' },
  { question: 'What is the overall time complexity of the Accounts Merge algorithm using Union-Find?', options: ['O(n²)', 'O(n log n)', 'O(n * alpha(n) + n log n)', 'O(n)'], correctAnswer: 'O(n * alpha(n) + n log n)', explanation: 'Union-Find operations take O(n * alpha(n)) and sorting emails in each merged group contributes O(n log n) overall.' },
  { question: 'Why must emails be sorted in the final merged account output?', options: ['To make Union-Find faster', 'Because the problem requires emails in sorted order for a consistent result', 'To remove duplicates', 'To identify the root email'], correctAnswer: 'Because the problem requires emails in sorted order for a consistent result', explanation: 'The problem specification requires that emails in each merged account are returned in sorted (lexicographic) order.' },
  { question: 'If account A has emails [x, y] and account B has emails [y, z], what happens after merging?', options: ['They remain separate', 'A and B are merged into one account with emails [x, y, z] sorted', 'Only email y is kept', 'A new account with all three emails is created separately'], correctAnswer: 'A and B are merged into one account with emails [x, y, z] sorted', explanation: 'Since A and B share email y, they belong to the same person. After merging, all unique emails [x, y, z] are combined and sorted.' },
  { question: 'What data structure is used to map email strings to integer indices before applying Union-Find?', options: ['Array', 'Stack', 'Hash Map', 'Queue'], correctAnswer: 'Hash Map', explanation: 'A hash map (dictionary) maps each unique email string to a unique integer index, allowing Union-Find to operate on integers instead of strings.' },
  { question: 'What optimization techniques are used in the Union-Find for Accounts Merge?', options: ['Lazy propagation and binary lifting', 'Path compression and union by rank', 'Coordinate compression and binary search', 'Memoization and divide and conquer'], correctAnswer: 'Path compression and union by rank', explanation: 'Path compression flattens the tree during find(), and union by rank keeps the tree balanced, together achieving near O(1) per operation.' },
  { question: 'Can two accounts with different names but a shared email be merged in this problem?', options: ['No, names must match for merging', 'Yes, shared email is the only condition for merging', 'Only if both names are substrings of each other', 'Only if they have more than one shared email'], correctAnswer: 'Yes, shared email is the only condition for merging', explanation: 'The problem states that accounts belong to the same person if they share an email, regardless of the name. The name from either account can be used.' },
  { question: 'What is the space complexity of the Union-Find structure used in Accounts Merge?', options: ['O(n²)', 'O(n log n)', 'O(n)', 'O(1)'], correctAnswer: 'O(n)', explanation: 'The parent and rank arrays each have size equal to the total number of unique emails n, giving O(n) space complexity.' },
];
